{
  "extends": ["airbnb", "airbnb/hooks"],
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
  "rules": {
    "new-cap": [2, { "capIsNewExceptions": ["List", "Map", "Set"] }],
    "react/no-multi-comp": 0,
    "import/default": 0,
    "import/no-duplicates": 0,
    "import/named": 0,
    "import/namespace": 0,
    "import/no-unresolved": 0,
    "import/no-named-as-default": 2,
    "comma-dangle": 0, 
    "indent": [2, 2, {"SwitchCase": 1}],    
    "no-console": 0,
    "no-alert": 0,    
    "linebreak-style": 0,
    "skipBlankLines": 0,
    "ignoreComments": 0
  }
}